# Generated by Django 5.0.7 on 2024-07-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_advertisement", models.IntegerField()),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("author", models.CharField(max_length=100)),
                ("count_view", models.IntegerField(default=0)),
                ("position", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
                "ordering": ["position"],
            },
        ),
    ]
