# Generated by Django 5.0.7 on 2024-07-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advertisement",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="description",
        ),
    ]
