# Generated by Django 5.0.7 on 2024-07-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_remove_advertisement_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="count_view",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="position",
            field=models.IntegerField(),
        ),
    ]
