# Generated by Django 5.0.7 on 2024-07-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_advertisement_count_view_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="author",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="title",
            field=models.CharField(),
        ),
    ]
