# Generated by Django 5.0.7 on 2024-07-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_advertisement_author_alter_advertisement_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
