# Generated by Django 5.0.7 on 2024-07-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_advertisement_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="id_advertisement",
            field=models.BigIntegerField(),
        ),
    ]
